######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 27 19:20:56 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h \
    paintarea.h
SOURCES += main.cpp mainwindow.cpp
