######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 6 10:07:46 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h paintarea.h \
    colorpick.h
SOURCES += main.cpp mainwindow.cpp
